title: "Ajay Bairwa"
email: bairwaajay770@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Ajay Bairwa, pursuing Electrical Engg. from Chartered Institute of Technology. Currently I'm Learning Front-End Web Development. 
  I'm Tech enthusiast and love to learn new skills for making better version of myself😊
baseurl: "/" 
url: "https://bairwa25.github.io/" 
twitter_username: bairwaa25
github_username:  bairwa25

sass:
  sass_dir: _sass

icon: ./assets/img/Ajay-Bairwa.jpg
